#
name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
      # comment
jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Post-Publish Job
    steps:
      - run: echo 'Replace with custom steps'
